version: '3.8'

services:
  clima-app-java:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WEATHER_API_KEY: ${WEATHER_API_KEY:-demo_key}
    container_name: clima-app-java
    ports:
      - "8080:8080"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY:-demo_key}
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - clima-network

networks:
  clima-network:
    driver: bridge
