name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main" ]
    paths:
      - 'aplicacionJava/**'
      - '.github/workflows/java.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'aplicacionJava/**'
      - '.github/workflows/java.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Definimos variables para versionado usando secretos o variables de GitHub
    env:
      MAJOR_VERSION: ${{ vars.JAVA_MAJOR_VERSION || '1' }}
      MINOR_VERSION: ${{ vars.JAVA_MINOR_VERSION || '0' }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven    
    - name: Build with Maven
      working-directory: aplicacionJava
      run: mvn -B package --file pom.xml

    - name: Run tests
      working-directory: aplicacionJava
      run: mvn test
      env:
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

    - name: Generate test report
      working-directory: aplicacionJava
      run: mvn jacoco:report

    - name: Check code quality
      working-directory: aplicacionJava
      run: |
        mvn compile
        echo "Verificación de calidad de código completada"
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
          
    - name: Login to Docker Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Genera la versión usando las variables de entorno y el número de ejecución del workflow    
    - name: Set version
      id: version
      run: echo "VERSION=${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ github.run_number }}" >> $GITHUB_OUTPUT
    - name: Build and push Docker image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v5
      with:
        context: ./aplicacionJava
        push: true
        build-args: |
          WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/clima-app-java:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/clima-app-java:${{ steps.version.outputs.VERSION }}
